### ISSUE TITLE
Practica Back End

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/practica-back-end-trabajo-is#2]
[Practica 7 Login para Back-end1.pdf](https://github.com/SistemasTecTlaxiaco/practica-back-end-trabajo-is/files/6549541/Practica.7.Login.para.Back-end1.pdf)

**Comment by EDITH-R** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
